backend:
  name: github
  repo: 39sho/decap-blog
  base_url: https://decap-blog.39sho.workers.dev/
  auth_endpoint: /api/auth
media_folder: "public/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "public/posts/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
